### ISSUE TITLE
[discuss] add_l10n need to pull from remote first

### ISSUE THREAD

**Issue by skyclouds2001** [xyy94813/mdn-site#1]
稍微看了下，在取原提交的哈希值的时候是取本地仓库（而不是远程仓库），可能会出现因为本地仓库和远程仓库不同步，从本地仓库提取的哈希值与从远程仓库提取的哈希值不同的情况；不过只要每次跑脚本时候提前使本地仓库和远程仓库同步一下就行（可以考虑加到脚本中？）

**Comment by xyy94813** [comment]
因为基于 github flow。
实际上还得自己的远程 fork 与 mdn 的同步。

此外，实现依赖于上面套了一层 workspace。
如果做成 cli 要考虑配置文件指定 两个仓库的地址。

我目前在尝试基于 git sub module，但是这貌似是一种 trick 的用法。

**Comment by skyclouds2001** [comment]
> 我目前在尝试基于 git sub module，但是这貌似是一种 trick 的用法。

git 的 submodule 的话也需要手动做仓库同步，感觉问题不在这儿

**Comment by xyy94813** [comment]
即便每次执行该脚本前 fetch and pull 远程仓库。
在最终 PR 合并前，仍有可能不同步。

该行为是一个改进项，但不能完全解决不同步的问题。

**Comment by skyclouds2001** [comment]
> 即便每次执行该脚本前 fetch and pull 远程仓库。
> 在最终 PR 合并前，仍有可能不同步。

确实

**Comment by skyclouds2001** [comment]
> 即便每次执行该脚本前 fetch and pull 远程仓库。
> 在最终 PR 合并前，仍有可能不同步。

我又想了一下，出现这种情况还是很少见的（除非合并翻译花了太多时间，但按 i18n-zh 的情况来看不太可能）

虽然说不是不可能，但可以忽略这种情况

**Comment by xyy94813** [comment]
我列一下可能存在的问题，然后一个一个解决吧。

- [ ] 脚本何时进行执行远程仓库更新？
- [x] ~如何保证从远程仓库 mdn/content 的 main 分支同步？~（`git pull https://github.com/mdn/content.git`）
- [ ] 如何保证本地的 content 的处于 main 分支？本地的 content 也处于修改文章状态（非 main 分支）？
- [ ] 是否需要考虑兼容  pull 失败？CN 地区 TSL 433 常态化问题是否需要考虑？

**Comment by xyy94813** [comment]
如果基于当前项目的 git 结构。
pull 和获取 content 下的文件的 commit hash 都需要先进入 ./content 目录下。

shell 脚本内部实现先基于映射关系重构一版本会好处理好多。

```mermaid
flowchart TD
   translated-content/files/zh-cn/web/**/*.md -- mapping--> content/files/en-us/web/**/*.md
   content/files/en-us/web/**/*.md --mapping--> files/en-us/web/**/*.md
   files/en-us/web/**/*.md --cd ./content and git rev-list-->  file_commit_hash
   file_commit_hash --cd mdn-site root and write_commit_hash--> translated-content/files/zh-cn/web/**/*.md
```

**Comment by xyy94813** [comment]
已经基于 command 重写，后续可以更方便的通过添加 option 的方式处理
